# model_name: TwoDofArm
# data_config_path: data_collection/data_config.yaml
# loop0_data_config_path: data_collection/loop0_data_config.yaml
# train_config_path: neural_network/configs/TwoDofArmModelTrainConfigTD.ini
# TD_loops: 1000
# NN_controller_name: NNManipulatorMPCController_eeTracker_point

# pretrained_weights_path: value_iteration/output/2026-04-30_04-10-00_TwoDofArm_VI_success_obs_SH/loop_10/training/model_epoch_15.pt

# resume_training: false
# loop_to_resume_from: 
# TD_dir: ""

# replay_buffer_capacity: 1000000


model_name: Pendulum
data_config_path: data_collection/data_config.yaml
loop0_data_config_path: data_collection/loop0_data_config.yaml
train_config_path: neural_network/configs/PendulumModelTrainConfigTD.ini
TD_loops: 1000
NN_controller_name: NNMPCController

pretrained_weights_path: value_iteration/output/2026-05-12_22-49-16_Pendulum_VI/loop_13/training/model_epoch_5.pt

resume_training: false
loop_to_resume_from: 
TD_dir: ""

replay_buffer_capacity: 500000