[DATA]
dataset_class = iiwa14Dataset_TD
log_space = true
data_path =

[CONFIG_MODEL_NAME]
model_name = iiwa14

[MODEL]
model_name = iiwa14Model
target_model_checkpoint_path =
online_model_checkpoint_path =
offline_model_checkpoint_path = 

[TRAINING]
n_step = 5
learning_rate = 0.0001
batch_size = 1024
gradient_steps = 5
target_tau = 0.0001
target_update_frequency = 2

[LOSS]
; weight for stationary-point penalty
alpha = 0.01
lam = 0.1
p_exp_up = 2.0
p_down = 0.90
ema_mse_tau = 0.05
ema_mse = 0