[DATA]
log_space = true
data_path =

[CONFIG_MODEL_NAME]
model_name = Pendulum

[MODEL]
model_name = PendulumModel
target_model_checkpoint_path =
online_model_checkpoint_path =

[TRAINING]
n_step = 5
learning_rate = 0.0003
batch_size = 1024
gradient_steps = 5
target_tau = 0.0005
target_update_frequency = 2

[LOSS]
; weight for stationary-point penalty
alpha = 0.1
; stationary point for pendulum (angle=0, angular_velocity=0)
x_s = [0.0, 0.0]
y_s = [0.0]